### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by mesqueeb** [mesqueeb/case-anything#23]
I tried 2.1.3 in my package and I ran into this error:

```js
} = require("case-anything");
    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/Sites/asyncapi-format/node_modules/case-anything/dist/index.umd.js from /Users/Sites/asyncapi-format/asyncapi-format.js not supported.
index.umd.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.umd.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/Sites/asyncapi-format/node_modules/case-anything/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Object.<anonymous> (/Users/Sites/asyncapi-format/asyncapi-format.js:21:5)
    at Object.<anonymous> (/Users/Sites/asyncapi-format/bin/cli.js:5:24) {
  code: 'ERR_REQUIRE_ESM'
```

Version 2.1.2 works without a problem.

_Originally posted by @thim81 in https://github.com/mesqueeb/case-anything/issues/20#issuecomment-1018747055_

**Comment by mesqueeb** [comment]
@thim81 fixed in latest version 🎉

**Comment by mesqueeb** [comment]
<img width="774" alt="image" src="https://user-images.githubusercontent.com/3253920/150794371-64efd59a-6f2d-47bd-8dd8-598a32ddf101.png">
